// Generated by: npx supabase gen types typescript --project-id grdeedwkzqyfxgfeskdr
// Re-run this command to regenerate after schema changes

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Tables: {
      outlets: {
        Row: {
          id: string
          name: string
          location: string | null
          code: string | null
          type: string | null
          is_active: boolean | null
          created_at: string | null
        }
        Insert: {
          id?: string
          name: string
          location?: string | null
          code?: string | null
          type?: string | null
          is_active?: boolean | null
          created_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          location?: string | null
          code?: string | null
          type?: string | null
          is_active?: boolean | null
          created_at?: string | null
        }
      }
      users: {
        Row: {
          id: string
          name: string
          email: string
          phone: string | null
          role: string | null
          outlet_id: string | null
          is_active: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id: string
          name: string
          email: string
          phone?: string | null
          role?: string | null
          outlet_id?: string | null
          is_active?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          email?: string
          phone?: string | null
          role?: string | null
          outlet_id?: string | null
          is_active?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
      }
      daily_accounts: {
        Row: {
          id: string
          outlet_id: string
          date: string
          sale_cash: string | null
          sale_upi: string | null
          sale_credit: string | null
          sale_return: string | null
          expenses: string | null
          purchase: string | null
          closing_stock: string | null
          created_by: string
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          outlet_id: string
          date: string
          sale_cash?: string | null
          sale_upi?: string | null
          sale_credit?: string | null
          sale_return?: string | null
          expenses?: string | null
          purchase?: string | null
          closing_stock?: string | null
          created_by: string
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          outlet_id?: string
          date?: string
          sale_cash?: string | null
          sale_upi?: string | null
          sale_credit?: string | null
          sale_return?: string | null
          expenses?: string | null
          purchase?: string | null
          closing_stock?: string | null
          created_by?: string
          created_at?: string | null
          updated_at?: string | null
        }
      }
      account_categories: {
        Row: {
          id: string
          name: string
          description: string | null
          type: string
          is_active: boolean | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          name: string
          description?: string | null
          type: string
          is_active?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          description?: string | null
          type?: string
          is_active?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
      }
      account_groups: {
        Row: {
          id: string
          name: string
          category_id: string
          description: string | null
          is_active: boolean | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          name: string
          category_id: string
          description?: string | null
          is_active?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          category_id?: string
          description?: string | null
          is_active?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
      }
      chart_of_accounts: {
        Row: {
          id: string
          code: string
          name: string
          group_id: string
          description: string | null
          balance_type: string
          is_active: boolean | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          code: string
          name: string
          group_id: string
          description?: string | null
          balance_type: string
          is_active?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          code?: string
          name?: string
          group_id?: string
          description?: string | null
          balance_type?: string
          is_active?: boolean | null
          created_at?: string | null
          updated_at?: string | null
        }
      }
      audit_logs: {
        Row: {
          id: string
          user_id: string | null
          user_name: string | null
          action: string
          entity_type: string
          entity_id: string | null
          old_data: Json | null
          new_data: Json | null
          ip_address: string | null
          created_at: string | null
        }
        Insert: {
          id?: string
          user_id?: string | null
          user_name?: string | null
          action: string
          entity_type: string
          entity_id?: string | null
          old_data?: Json | null
          new_data?: Json | null
          ip_address?: string | null
          created_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string | null
          user_name?: string | null
          action?: string
          entity_type?: string
          entity_id?: string | null
          old_data?: Json | null
          new_data?: Json | null
          ip_address?: string | null
          created_at?: string | null
        }
      }
      notifications: {
        Row: {
          id: string
          user_id: string
          title: string
          message: string
          type: string | null
          is_read: boolean | null
          created_at: string | null
        }
        Insert: {
          id?: string
          user_id: string
          title: string
          message: string
          type?: string | null
          is_read?: boolean | null
          created_at?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          message?: string
          type?: string | null
          is_read?: boolean | null
          created_at?: string | null
        }
      }
      registration_requests: {
        Row: {
          id: string
          name: string
          email: string
          phone: string | null
          status: string | null
          reviewed_by: string | null
          created_at: string | null
          updated_at: string | null
        }
        Insert: {
          id?: string
          name: string
          email: string
          phone?: string | null
          status?: string | null
          reviewed_by?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
        Update: {
          id?: string
          name?: string
          email?: string
          phone?: string | null
          status?: string | null
          reviewed_by?: string | null
          created_at?: string | null
          updated_at?: string | null
        }
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
  }
}
