// Auto-generated by `npx boneyard-js build`
// Run that command with the dev server active to regenerate this file with captured bones.
import { registerBones } from 'boneyard-js/react';
registerBones({});
