"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js/react'

import _dashboard_kpis from './dashboard-kpis.bones.json'
import _dashboard_outlets from './dashboard-outlets.bones.json'
import _reports_table from './reports-table.bones.json'

registerBones({
  "dashboard-kpis": _dashboard_kpis,
  "dashboard-outlets": _dashboard_outlets,
  "reports-table": _reports_table,
})
